// app/api/finance/route.ts
import { generateStructuredContent, isApiConfigured } from "@/lib/gemini-server";
import { PERSONAS } from "@/lib/gemini";
import { FinancialOutlookSchema, FinancialOutlookOutputSchema } from "@/lib/schemas";
import { NextResponse } from "next/server";
import { ZodError, z } from "zod";

export const runtime = "nodejs";

export async function POST(req: Request) {
  try {
    if (!isApiConfigured()) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const body = await req.json();
    const validation = FinancialOutlookSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        { error: validation.error.issues[0].message },
        { status: 400 }
      );
    }

    const { businessModel, costStructure, currentStage } = validation.data;

    const prompt = `${PERSONAS.CFO}

Business Model: ${businessModel}
Cost Structure Main Drivers: ${costStructure}
Current Stage: ${currentStage}`;

    const result = await generateStructuredContent(prompt, FinancialOutlookOutputSchema) as z.infer<typeof FinancialOutlookOutputSchema>;

    // Ensure colors are present for charts if not generated by AI
    const colorfulResult = {
      ...result,
      costBreakdown: result.costBreakdown.map((item, index) => ({
        ...item,
        color: item.color || [
          "#8884d8", "#82ca9d", "#ffc658", "#ff8042", "#0088FE", "#00C49F"
        ][index % 6]
      }))
    };

    return NextResponse.json(colorfulResult, {
      headers: {
        "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
      },
    });

  } catch (error) {
    if (error instanceof ZodError) {
      return NextResponse.json(
        { error: "Invalid response format from AI" },
        { status: 502 }
      );
    }

    console.error("Error in financial outlook:", error);
    
    const errorMessage = error instanceof Error ? error.message : String(error);

    if (errorMessage.includes("API_KEY") || errorMessage.includes("401") || errorMessage.includes("403")) {
      return NextResponse.json(
        { error: "Invalid API Key. Please check your GEMINI_API_KEY." },
        { status: 500 }
      );
    }

    if (errorMessage.includes("429") || errorMessage.includes("quota")) {
      return NextResponse.json(
        { error: "Rate limit exceeded. Please wait a minute and try again." },
        { status: 429 }
      );
    }

    return NextResponse.json(
      { error: `Failed to generate financial outlook: ${errorMessage}` },
      { status: 500 }
    );
  }
}
